services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: syphe
      POSTGRES_PASSWORD: syphe
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  servicereg:
    image: syph3/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
      - microservice_network

networks:
  postgres:
    driver: bridge
  microservice_network:
    driver: bridge

volumes:
  postgres:
  pgadmin: